apiVersion: apps/v1
kind: Deployment
metadata:
  name: gist-web
  labels:
    app: gist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gist
  template:
    metadata:
      namespace: gist
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '9090'
        prometheus.io/scrape: 'true'
      labels:
        app: gist
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: gist-server
          image: rg.nl-ams.scw.cloud/cloud-skadi/gist-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 9090
          args:
            - "-Dlogback.configurationFile=logback-production.xml"
          env:
            - name: IS_PRODUCTION
              value: "TRUE"
            - name: SQL_HOST
              value: "postgres:5432"
            - name: SQL_DB
              value: "skadi-gist"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gist-data
                  key: db-password
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: gist-data
                  key: db-user
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: gist-data
                  key: github-secret
            - name: GITHUB_ID
              valueFrom:
                secretKeyRef:
                  name: gist-data
                  key: github-id
            - name: COOKIE_SALT
              valueFrom:
                secretKeyRef:
                  name: gist-data
                  key: cookie-salt
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gist-data
                  key: s3-access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gist-data
                  key: s3-secret-key
            - name: S3_BUCKET_NAME
              value: cloud-skadi-gist
            - name: S3_ENDPOINT
              value: https://cloud-skadi-gist.s3.nl-ams.scw.cloud
            - name: S3_REGION
              value: nl-ams
            - name: STORAGE_KIND
              value: s3
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: gist-data
                  key: sentry-dsn

          resources:
            requests:
              memory: "350Mi"
              cpu: "0.1"
            limits:
              memory: "2000Mi"
              cpu: "2.0"
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /health
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gist-frontend
spec:
  selector:
    app: gist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
