# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release Container

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 11
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: rg.nl-ams.scw.cloud/cloud-skadi
        username: nologin
        password: ${{ secrets.SCALEWAY_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v5.0.0
      with:
        images: |
          rg.nl-ams.scw.cloud/cloud-skadi/gist-server
          ${{ secrets.DOCKER_HUB_USERNAME }}/gist-server
        tags: |
          type=semver,pattern={{version}}
    - name: Build with Gradle
      run: ./gradlew :server:installDist --no-daemon
    - name: build docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: server
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        build-args: release=${{ steps.vars.outputs.tag }}

