# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release Container

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: rg.nl-ams.scw.cloud/cloud-skadi
        username: nologin
        password: ${{ secrets.SCALEWAY_TOKEN }}

    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v3.6.0
      with:
        images: rg.nl-ams.scw.cloud/cloud-skadi/gist-server
        tags: |
          type=semver,pattern={{version}}
    - name: Build with Gradle
      run: ./gradlew :server:installDist --no-daemon
    - name: build docker images
      uses: docker/build-push-action@v2.7.0
      with:
        context: server
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        build-args: release=${{ steps.vars.outputs.tag }}

